### ISSUE TITLE
No Vendor assigned when copying Resource

### ISSUE THREAD

**Issue by wennersten** [wennersten/tjanstekollen#11]
When Vendor copies a Resource and saves it the it is not assigned the current Vendor, the Vednor field is empty. Should be assigned to the Vendor that makes the copy, i.e. teh Vendor who owns the Resource that is copied.

**Comment by wennersten** [comment]
No, it do not work. I used the Copy Resource button from the Vendor dashboard and did a copy of the Resource Läsappen3 to Läsappen4, it did not get the Vendor Lärmedia assigned but is blank on Vendor field.

**Comment by jaya-drapcode** [comment]
I have fixed this, please check if there will be any issue after this we can arrange a call to discuss.

**Comment by wennersten** [comment]
Works fine now
