### ISSUE TITLE
Add info about role on Vendor Profile page

### ISSUE THREAD

**Issue by wennersten** [wennersten/tjanstekollen#12]
I think it would be good if the Vendor could see his own role when viewing his profile.

![image](https://github.com/wennersten/tjanstekollen/assets/3404603/f8e0ba15-9dc8-4a21-8a84-71b4d42c7e32)

**Comment by jaya-drapcode** [comment]
It is resolved!
![Screenshot (1068)](https://github.com/wennersten/tjanstekollen/assets/146457331/93bf114e-5c57-4389-a691-596a0e0116d7)
