### ISSUE TITLE
New Table for Vendor and adjustment to exsting

### ISSUE THREAD

**Issue by wennersten** [wennersten/tjanstekollen#23]
It should not be possible for a Vendor to update the information for a Resource that has status=Archived.

Due do that, make the following adjustments to the table showing Not Active Resources.
1.Change the to titel of the table to Resources under construction and chnage so that Resources with status=Registered, In Progress and Ready for activation is visible in this table. Should have the buttons Show and Update. Remove the serach dropdown with status.

2.Next is the existing table Active Resources that should be as it is.

3.Create a new table wit the title=Archived Resources, that only includes Archived Resources. Search dropdown same as for table with Actibe Resources. This table should have buttons for Show and Copy Resource - not update or delete.

**Comment by jaya-drapcode** [comment]
Resolved.
![Screenshot (1078)](https://github.com/wennersten/tjanstekollen/assets/146457331/8a2bd060-77c9-4c08-93b2-963717124aaf)
![Screenshot (1079)](https://github.com/wennersten/tjanstekollen/assets/146457331/5f094bb0-eaa4-470f-a10c-9736bb9498fa)
