### ISSUE TITLE
Message to Vendor when Not Approving Resource

### ISSUE THREAD

**Issue by wennersten** [wennersten/tjanstekollen#25]
When SuperAdmin do nott approve a Resource sent as Ready For Activation and SuperAdmin wants the Vendor to cahnhe/update som information, he clicks the button Reject se below.

![image](https://github.com/wennersten/tjanstekollen/assets/3404603/e5691b1c-8836-4bea-9b5c-6cf82bf9d34e)

I would like you to have a popup (snippet?) to come forward when SuperAdmin clicks reject, in that popup SuperAdmin can fill in a text describing what the vendor should change/update in order to send for Activation again. I have cerated a field in the Resource Collection called VendorReply to hold that information. I would suggest to show this text for the Vendor by having an extra button in the Table called Resources under construction, the button could be called Notifications and bring forward a popup with the text enterted in VendorReply by SuperAdmin, The Vendor should be able to also edit the text in the box and save it.

You also then need to create a button to view this notifications in the Resource table for SuperAdmin.

**Comment by jaya-drapcode** [comment]
I am working on it.

**Comment by jaya-drapcode** [comment]
(The Vendor should be able to also edit the text in the box and save it.) When Vendor will update/edit the vendor reply - what should be the resource status?

**Comment by jaya-drapcode** [comment]
Resolved. 
Please test. 
![Screenshot (1083)](https://github.com/wennersten/tjanstekollen/assets/146457331/03818714-6468-4c64-9ec6-e6ca2fec2363)
![Screenshot (1087)](https://github.com/wennersten/tjanstekollen/assets/146457331/f96890e8-bf02-4dc7-8f68-0a9d7af72b7e)
![Screenshot (1086)](https://github.com/wennersten/tjanstekollen/assets/146457331/daec4b69-5e29-4629-a83d-8094310072e4)
![Screenshot (1085)](https://github.com/wennersten/tjanstekollen/assets/146457331/2ec93347-8453-481d-91b1-4af38543d714)
![Screenshot (1084)](https://github.com/wennersten/tjanstekollen/assets/146457331/3d7dea60-7c6d-4a58-bf3c-6dd48d51e6c7)

**Comment by wennersten** [comment]
I can not see the functionallity you show above. It is not present in production for me?

**Comment by jaya-drapcode** [comment]
Please share the url or production in which you are checking. 
Are you able to see the notification button?
On which pages are you checking, please provide me the details.

**Comment by jaya-drapcode** [comment]
From the super admin side -  after login as super admin >> menu>> approvals>> resources 
When you will click on reject button you will get confirmation popup as "Do you want to disapprove?" , if you will select yes then you will get a pop where super admin can enter the details of disapproving the resource.

**Comment by jaya-drapcode** [comment]
From vendor side, login as vendor admin/member >> menu>> resources
You will see a button of notification in the table " Resources under construction". When you will click on it you will get popup, where vendor can edit or add new reply.

Super Admin can view the notification by going to >>menu>>resources>> in the table there is notification button.

**Comment by jaya-drapcode** [comment]
![Screenshot (1100)](https://github.com/wennersten/tjanstekollen/assets/146457331/b3cbd844-eaed-4728-8c62-12db8a6b18d0)

Super Admin >> Menu >> Approvals >> Resources

**Comment by jaya-drapcode** [comment]
![Screenshot (1101)](https://github.com/wennersten/tjanstekollen/assets/146457331/c4998970-7175-4add-a2cc-8d8af075ad53)

After selecting Yes, Popup appears

**Comment by jaya-drapcode** [comment]
![Screenshot (1102)](https://github.com/wennersten/tjanstekollen/assets/146457331/17a7201a-a7e4-44c2-a213-830059b0f3ae)

Now the status will change so the records will not show in the same table as it is not in the status (Ready for activation), so the record will show in the resource page (Super Admin >> Menu >> Resources). Click on the notification button.

**Comment by jaya-drapcode** [comment]
![Screenshot (1103)](https://github.com/wennersten/tjanstekollen/assets/146457331/4db7fd1c-d08c-4b76-a440-9ebcde83a219)

This popup is to view the replies.

**Comment by wennersten** [comment]
Ok, I see. Please also add notification button to Vendor Dashboard

**Comment by jaya-drapcode** [comment]
Added!
