### ISSUE TITLE
Can no set Asseement for Resource

### ISSUE THREAD

**Issue by wennersten** [wennersten/tjanstekollen#27]
When trying ot make an assesment there are no statuses to chose from

![image](https://github.com/wennersten/tjanstekollen/assets/3404603/58c5ba01-1f28-4e25-a724-dd4f246589ee)

**Comment by jaya-drapcode** [comment]
Resolved!
![Screenshot (1077)](https://github.com/wennersten/tjanstekollen/assets/146457331/dd8c7f2a-f822-430e-b9d1-b94a332187b5)
