### ISSUE TITLE
Can not serach for Resource

### ISSUE THREAD

**Issue by wennersten** [wennersten/tjanstekollen#28]
When SchoolAdmin chooses the menu option Resiurce, the serach filed above the table do not work

**Comment by jaya-drapcode** [comment]
It is working now.
![Screenshot (1057)](https://github.com/wennersten/tjanstekollen/assets/146457331/f3f7eb28-e61c-4eb9-b58b-44a21659b481)

**Comment by jaya-drapcode** [comment]
![Screenshot (1059)](https://github.com/wennersten/tjanstekollen/assets/146457331/012f5f3b-218c-4fe1-bc60-3b3fcbe26286)

**Comment by wennersten** [comment]
No it is not working for me. @jaya-drapcode

**Comment by jaya-drapcode** [comment]
Can you please share the screenshot with the fields you have selected in the search and page name, so that I can check?
As it is working for me.

**Comment by jaya-drapcode** [comment]
![Screenshot (1062)](https://github.com/wennersten/tjanstekollen/assets/146457331/d1fff67e-db45-415b-ab97-7264a9e650ff)

**Comment by jaya-drapcode** [comment]
Please also let me know if you are checking in production environment or beta environment.

**Comment by wennersten** [comment]
I always check  using the Production environment, Vishal told me to do that.
