### ISSUE TITLE
REmove CSV button

### ISSUE THREAD

**Issue by wennersten** [wennersten/tjanstekollen#30]
![image](https://github.com/wennersten/tjanstekollen/assets/3404603/6b10a081-593d-4cee-bb40-091063a89dd7)

**Comment by jaya-drapcode** [comment]
Resolved!  Removed CSV button.
![Screenshot (1070)](https://github.com/wennersten/tjanstekollen/assets/146457331/c5ca9080-782d-43b7-b2e5-206ae3ab0b11)
