### ISSUE TITLE
Translate 

### ISSUE THREAD

**Issue by wennersten** [wennersten/tjanstekollen#31]
In the Pedagogic Assesment there is 3 statuses, I do not think they are linked to localization. Could you please change that so Yes=Ja, No=Nej and Partially=Delvis

![image](https://github.com/wennersten/tjanstekollen/assets/3404603/f546bcff-5264-4245-925c-f8d1675b301f)

**Comment by jaya-drapcode** [comment]
Resolved!
![Screenshot (1111)](https://github.com/wennersten/tjanstekollen/assets/146457331/b2b5893f-c02c-47e2-a383-403685b275ed)
