### ISSUE TITLE
Search boxes för Assesements do not work

### ISSUE THREAD

**Issue by wennersten** [wennersten/tjanstekollen#32]
Threee of the search boxes over the Assesments do not work. Please fix. Why does this keep coming back?
![image](https://github.com/wennersten/tjanstekollen/assets/3404603/4d99d582-afe7-4c81-b28f-070967293247)

**Comment by jaya-drapcode** [comment]
It is working fine for me. I have checked in all the environments.
Please clear the Cache and try again.

![Screenshot (1113)](https://github.com/wennersten/tjanstekollen/assets/146457331/62d466c2-7348-4a1d-acb6-09856c7f236e)
![Screenshot (1114)](https://github.com/wennersten/tjanstekollen/assets/146457331/5223f4f5-e7c6-4096-83d1-2805d141e1a8)
